apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: banter-bus-core-api
  namespace: "78358389381"
  selfLink: /apis/serving.knative.dev/v1/namespaces/78358389381/services/banter-bus-core-api
  creationTimestamp: "2021-12-19T23:04:49.349876Z"
  labels:
    cloud.googleapis.com/location: europe-west1
  annotations:
    run.googleapis.com/client-name: cloud-console
    serving.knative.dev/creator: hmajid2301@gmail.com
    serving.knative.dev/lastModifier: hmajid2301@gmail.com
    client.knative.dev/user-image: eu.gcr.io/banter-bus/banter-bus-core-api
    run.googleapis.com/launch-stage: BETA
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      name: banter-bus-core-api
      annotations:
        run.googleapis.com/client-name: cloud-console
        client.knative.dev/user-image: eu.gcr.io/banter-bus/banter-bus-core-api
        run.googleapis.com/execution-environment: gen2
        autoscaling.knative.dev/maxScale: "3"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: banter-bus@appspot.gserviceaccount.com
      containers:
        - image: eu.gcr.io/banter-bus/banter-bus-core-api
          ports:
            - name: http1
              containerPort: 8080
          env:
            - name: BANTER_BUS_CORE_API_WEB_HOST
              value: "0.0.0.0"
            - name: BANTER_BUS_CORE_API_WEB_PORT
              value: "8080"
            - name: BANTER_BUS_CORE_API_DB_USERNAME
              value: banter-bus
            - name: BANTER_BUS_CORE_API_DB_HOST
              value: banter-bus-database.ffljl.mongodb.net
            - name: BANTER_BUS_CORE_API_DB_NAME
              value: core_api
            - name: BANTER_BUS_CORE_API_DB_SCHEMA
              value: mongodb+srv
            - name: BANTER_BUS_CORE_API_ENVIRONMENT
              value: production
            - name: BANTER_BUS_CORE_API_CLIENT_ID
              value: 78358389381-o5nq31qc9ntq5evfg03n4565cjbf8qpo.apps.googleusercontent.com
            - name: BANTER_BUS_CORE_API_USE_AUTH
              value: "True"
            - name: BANTER_BUS_CORE_API_MANAGEMENT_API_URL
              value: https://management.api.banterbus.games
            - name: BANTER_BUS_CORE_API_MESSAGE_QUEUE_HOST
              value: redis-13370.c299.asia-northeast1-1.gce.cloud.redislabs.com
            - name: BANTER_BUS_CORE_API_MESSAGE_QUEUE_PORT
              value: "18607"
            - name: BANTER_BUS_CORE_API_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: banter-bus-db-password
            - name: BANTER_BUS_CORE_API_MESSAGE_QUEUE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: banter-bus-redis-password
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
  traffic:
    - percent: 100
      latestRevision: true
status:
  conditions:
    - type: Ready
      status: "True"
    - type: ConfigurationsReady
      status: "True"
    - type: RoutesReady
      status: "True"
  url: https://banter-bus-core-api-x6ccwlffzq-ew.a.run.app
  address:
    url: https://banter-bus-core-api-x6ccwlffzq-ew.a.run.app
